server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_group
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: GroupService

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
